### ISSUE TITLE
bam file header info in rerun lanes

### ISSUE THREAD

**Issue by percyfal** [SciLifeLab/bcbb#190]
The description tag is used to annotate bam files. Therefore, for rerun/mixed lanes, some samples will be annotated with a wrong project descriptor.

Example

```
description: ProjectA
multiplex:
- barcode_id: 1
  name: SampleA
  sample_prj: ProjectA
- barcode_id: 2
  name: SampleB
  sample_prj: ProjectB
```

SampleB will be annotated with ProjectA.
